### ISSUE TITLE
Is this project open for contributions?

### ISSUE THREAD

**Issue by kal-nemi** [ankushkhanna1998/movie-selector#1]
I tried and tested the file in my local system and it's working fine. So, I would love to contribute in it.

**Comment by ankushkhanna1998** [comment]
Sure, if you have any suggestions, we can review and work on them. Don't hesitate mentioning about them here.
You can anyway open a pull request.

**Comment by ankushkhanna1998** [comment]
Closing this issue for now. In case you feel the need, you can reopen this issue, or for any constructive contribution, you can open a pull request. Thank you.

**Comment by kal-nemi** [comment]
Yes of course ! Thank you So much
